VERSION = "1.0"
TOKENS_URL_CHUNK = "/tokens"
CHARGE_URL_CHUNK = "/charge"
VOID_URL_CHUNK = "/void"
DEFERRED_URL_CHUNK = "/deferred"
PARAMETER_MERCHANT_ID = "merchant_identifier"
PARAMETER_LANGUAGE = "language_indicator"
PARAMETER_REMEMBER_ME = 'remember_me'
PARAMETER_TRANSACTION_TOKEN = "transaction_token"
PARAMETER_TRANSACTION_TICKET = "ticket_number"
PARAMETER_TRANSACTION_ID = "transaction_id"
PARAMETER_CURRENCY_CODE = "currency_code"
PARAMETER_TRANSACTION_AMOUNT = "transaction_amount"
PARAMETER_TICKET_NUMBER = "ticket_number"
PARAMETER_DO_NOT_EXIST = "Parameter does not exist"
PARAMETER_CARD = "card"
PARAMETER_CARD_NAME = "name"
PARAMETER_CARD_NUMBER = "number"
PARAMETER_CARD_EXP_MONTH = "expiry_month"
PARAMETER_CARD_EXP_YEAR = "expiry_year"
PARAMETER_CARD_CVC = "cvv"
PARAMETER_DEFERRED = "deferred"
PARAMETER_MONTHS = "months"
PARAMETER_INTEREST = "rate_of_interest"
PARAMETER_ERRORS = "error"
PARAMETER_ERRORS_MESSAGE = "message"
PARAMETER_ERRORS_CODE = "code"
CONTENT_TYPE = "application/json"
KUSHKI_PUBLIC_KEY = """-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC81t5iu5C0JxYq5/XNPiD5ol3Z
w8rw3LtFIUm7y3m8o8wv5qVnzGh6XwQ8LWypdkbBDKWZZrAUd3lybZOP7/82Nb1/
noYj8ixVRdbnYtbsSAbu9PxjB7a/7LCGKsugLkou74PJDadQweM88kzQOx/kzAyV
bS9gCCVUguHcq2vRRQIDAQAB
-----END PUBLIC KEY-----"""